version: '3.8'

services:

  # Redis Cache Container
  redis:
    image: redis:alpine
    container_name: worker_allocation_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Node.js Express Backend & Socket.io Server Container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worker_allocation_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 5000
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: worker_allocation_db
      JWT_SECRET: super_secret_worker_allocation_key_2026
      REDIS_URL: redis://redis:6379
    ports:
      - "5010:5000"
    depends_on:
      - redis
    networks:
      - app-network

  # React Frontend Container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: worker_allocation_frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
